CC=gcc -Wall  -lefence
CFLAGS= 
DEPS =  ../libs/fileHandler.c ../libs/stringHandler.c ../libs/occorrenza.c Hal_m.c ../libs/printer.c ../libs/parameterHandler.c 
c:
	$(CC)  $(CFLAGS) $(DEPS) -g -O0 -o hal   
